### ISSUE TITLE
Spring cloud bus and cloud stream kafka simultaneous usage conflict

### ISSUE THREAD

**Issue by gelluszi** [spring-cloud/spring-cloud-stream-binder-kafka#1049] opened 2021-03-23 15:41 UTC
**Bug description**
Setting both **org.springframework.cloud:spring-cloud-bus** and **org.springframework.cloud:spring-cloud-starter-stream-kafka** as dependency for a spring boot application and configuring cloud bus and multiple kafka binders with custom environment settings the following exception is thrown during startup:

g.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@4fd74223 has not been refreshed yet
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.4.jar:5.3.4]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_211]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:934) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:585) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:326) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) [spring-boot-2.4.3.jar:2.4.3]
        at my.projects.apps.NotificationApplication.main(NotificationApplication.java:10) [main/:na]
Caused by: java.lang.IllegalStateException: org.springframework.context.annotation.AnnotationConfigApplicationContext@4fd74223 has not been refreshed yet
        at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1140) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.AbstractApplicationContext.getBeanProvider(AbstractApplicationContext.java:1182) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.cloud.context.restart.RestartEndpoint.onApplicationEvent(RestartEndpoint.java:95) ~[spring-cloud-context-3.0.1.jar:3.0.1]
        at org.springframework.cloud.context.restart.RestartEndpoint.onApplicationEvent(RestartEndpoint.java:53) ~[spring-cloud-context-3.0.1.jar:3.0.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:420) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:377) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.cloud.stream.binder.DefaultBinderFactory$1.onApplicationEvent(DefaultBinderFactory.java:294) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:131) ~[spring-context-5.3.4.jar:5.3.4]
        at org.springframework.boot.context.event.EventPublishingRunListener.contextLoaded(EventPublishingRunListener.java:100) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplicationRunListeners.lambda$contextLoaded$4(SpringApplicationRunListeners.java:71) ~[spring-boot-2.4.3.jar:2.4.3]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_211]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:117) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:111) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplicationRunListeners.contextLoaded(SpringApplicationRunListeners.java:71) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:414) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:325) [spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:144) ~[spring-boot-2.4.3.jar:2.4.3]
        at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinderInstance(DefaultBinderFactory.java:326) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binder.DefaultBinderFactory.doGetBinder(DefaultBinderFactory.java:215) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binder.DefaultBinderFactory.getBinder(DefaultBinderFactory.java:143) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binding.BindingService.getBinder(BindingService.java:379) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:102) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_211]
        at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.1.jar:3.1.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.4.jar:5.3.4]
        ... 15 common frames omitted

**Sample**

**gradle.build**:
```
buildscript {
   dependencies {
        classpath group: 'io.spring.gradle', name: 'dependency-management-plugin', version: '1.0.11.RELEASE'
        classpath group: 'org.springframework.boot', name: 'spring-boot-gradle-plugin', version: '2.4.3'
    }
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:2.4.3"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2020.0.1"
    }
}

dependencies {
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-actuator'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-mail'
    implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web'

    implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-config'
    implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-bus-kafka'
}
```

**application.yaml**:
```
spring:
  cloud:
    discovery:
      enabled: false
    bus:
      enabled: true
      trace:
        enabled: false
      destination: my-cloud-bus-local
      id: my-config-server
      refresh:
        enabled: true
      env:
        enabled: true
    function:
      definition: myEventConsumer
    stream:
      bindings:
        my-cloud-bus:
          destination: my-cloud-bus-local
          binder: kafka-bus-message
        myEventConsumer-in-0:
          destination: event-message-local
          binder: kafka-event-message
      binders:
        kafka-bus-message:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost
                      configuration:
                        "[security.protocol]": Plaintext
        kafka-event-message:
          type: kafka
          environment:
            spring:
              cloud:
                stream:
                  kafka:
                    binder:
                      brokers: localhost
                      configuration:
                        "[security.protocol]": Plaintext
```

**Workaround 1.**
If I drop/comment the environment settings from the Kafka binders the application will start and use the default Kafka environment settings:

binders:
```
 kafka-bus-message:
    type: kafka
 kafka-event-message:
    type: kafka
```

**Workaround 2.**
Checking some earlier spring boot and spring cloud versions I found the above problem is not present if I set the following versions:

springBootVersion = '2.4.0-M3'
springCloudVersion = '2020.0.0-M4'

However, the following new error message is logged (it's not blocking my actual task):
2021-03-05 15:57:44.343 INFO 32392 --- [pool-4-thread-1] i.m.c.i.binder.kafka.KafkaMetrics : Failed to bind meter: kafka.consumer.fetch.manager.records.consumed.total [tag(client-id=consumer-anonymous.7c914275-a40a-4cf6-9568-ee7938448ff6-4), tag(topic=iss-cloud-bus-local), tag(kafka-version=2.6.0), tag(spring.id=my-cloud-bus-local.consumer.consumer-anonymous.7c914275-a40a-4cf6-9568-ee7938448ff6-4)]. However, this could happen and might be restored in the next refresh.
Right after the startup, these kinds of logs disappear.

**Comment by sobychacko** [comment] 2021-03-23 20:59
@gelluszi Could you share a small minimal sample where we can reproduce this issue? Thanks.

**Comment by gelluszi** [comment] 2021-03-24 09:22
Hi,

Attached you can find a mini app to demonstrate the issue.

Cheers,
Istvan Gelle

From: Soby Chacko ***@***.***>
Sent: 2021. március 23., kedd 22:00
To: spring-cloud/spring-cloud-stream-binder-kafka ***@***.***>
Cc: Istvan Gelle ***@***.***>; Mention ***@***.***>
Subject: [External] : Re: [spring-cloud/spring-cloud-stream-binder-kafka] Spring cloud bus and cloud stream kafka simultaneous usage conflict (#1049)


@gelluszi<https://urldefense.com/v3/__https:/github.com/gelluszi__;!!GqivPVa7Brio!KYgREBBk7dDBDZS45OCW_qTAvyhf45CI4ffnmutKREs-Ry7Eyxtbnb6kjYrX1qIc9w$> Could you share a small minimal sample where we can reproduce this issue? Thanks.

**Comment by sobychacko** [comment] 2021-03-24 20:52
@gelluszi I tried to run your project and it gave me trouble on the IDE and did not build properly. Here is a sample application that uses multi binder Kafka support: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/multi-binder-samples/multi-binder-two-kafka-clusters

Could you use this as a basis to reproduce your issues? Upgrade the proper version of boot and cloud and add necessary dependencies of bus. That way it will really help us to debug the issue. Or make the sample you shared as simple as possible with enough instructions to run it on our end. Thanks!

**Comment by gelluszi** [comment] 2021-03-25 07:43
To run the app is straightforward (you don't need any IDE):

1. Unzip my-app.zip
2. cd my-app
3. ./dev-boot-run.sh

**Comment by gelluszi** [comment] 2021-03-25 10:31
To run the app is straightforward (you don't need any IDE):

1. Unzip my-app.zip
2. cd my-app
3. ./dev-boot-run.sh

**Comment by gelluszi** [comment] 2021-03-25 10:36
I've tried the sample application and found it works fine with the following versions:
```
springBootVersion = '2.4.4'
springCloudVersion = '2020.0.2'
```

I also tested it successfully with the following versions:
```
springBootVersion = '2.4.3'
springCloudVersion = '2020.0.1'
```

However, my application works only with the versions (I'm fine with it):
```
springBootVersion = '2.4.4'
springCloudVersion = '2020.0.2'
```

One difference between the 2 apps is that my one uses also cloud bus and cloud config.

**Comment by sobychacko** [comment] 2021-03-25 15:05
@gelluszi Could you clarify the above comment? Did it fail with `2.4.4/2020.0.2` combination? and only worked in the `2.4.3/2020.0.1` combination? As I asked above, any chance you can use the sample as a basis as it is (since it works) and add components necessary to make it break? That way we know exactly what component caused the failure and troubleshoot.

**Comment by gelluszi** [comment] 2021-03-25 15:35
Here are the dependencies along with versions which cause the trouble in my app:

```
ext {
        springBootVersion = '2.4.3'
        springCloudVersion = '2020.0.1'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

dependencies {
    implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-config'
    implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-bus-kafka'
}
```
If I exclude the cloud bus dependency the app will start.

**Comment by sobychacko** [comment] 2021-03-25 15:37
Does that mean `2.4.4`/`2020.0.2` combination work, even with bus dependency included?

**Comment by gelluszi** [comment] 2021-03-25 15:41
Yes

**Comment by sobychacko** [comment] 2021-03-25 15:45
Why can't you upgrade to that combination then, since they are point releases? My point is that, if it is indeed due to some bugs in the `2.4.3/2020.0.1` combination, obviously those are addressed in `2.4.4/2020.0.2`. In other words, there is nothing to fix since the latest point releases work fine.

**Comment by gelluszi** [comment] 2021-03-25 15:46
Ok, as I wrote I am okay now with the newer versions.

**Comment by sobychacko** [comment] 2021-03-25 15:50
Ah ok. I missed following that part. Now it makes sense. Thank you!! Closing the issue.

**Closed by sobychacko** 2021-03-25 15:50 UTC
