### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by ltalhouarne** [spring-cloud/spring-cloud-stream-binder-kafka#71] opened 2016-11-17 22:21 UTC
While getting started with spring-cloud-stream I have noticed poor performance regardless of the committing strategy.

The details of my benchmarking can be found here: 

http://stackoverflow.com/questions/40665418/spring-cloud-stream-kafka-binder-performance/40665898#40665898

In a nutshell, while the kafka-consumer.sh provided by the kafka library is taking a few seconds to consume 96k messages, the following code however: 

```
private int i = 0;

    @StreamListener(Sink.INPUT)
    public void processMessage(Message<?> message) {
         i++;
    }

    @Scheduled(fixedDelay=5000)
    private void scheduled(){
        LOG.info("Messages consumed: " + i);
    }
```

takes close to **1 minute**.

I am using version 1.1.0 of spring-cloud-stream, Kafka .9 with a topic that has 1 partition and the messages' individual size is 723 bytes.

**Comment by ltalhouarne** [comment] 2016-11-18 00:10
I just tried using kafka-integration 2.0.0 directly and I am experiencing the same behavior.

I used the following example: https://github.com/spring-projects/spring-integration-samples/blob/master/basic/kafka/src/main/java/org/springframework/integration/samples/kafka/Application.java

I tried with both a `PollableChannel` and a `SubscribableChannel`.

**Comment by mbogoevici** [comment] 2016-11-18 00:20
@ltalhouarne 
Thanks for reporting this and also for following up - I believe this might be caused by something lower down the stack, so I added an issue in Spring Kafka - once we have a baseline we can assess whether there is some binder related overhead.

**Comment by mbogoevici** [comment] 2016-11-18 04:21
As indicated in https://github.com/spring-projects/spring-kafka/issues/204 this may have something to do with macOS being used for testing. Linux shows a different profile. There are still differences between the binder and the native client, but my local tests on Linux show about 250K msgs/second with the binder (at 1000 bytes per message), vs 500K msgs/second with the Spring Kafka client (and slightly higher values with just the native client). However, this is very different from the 95K messages in 60 seconds (roughly 1500 msgs/second) reported initially, and any micro-optimizations might be largely offset by any useful application code.

**Comment by mbogoevici** [comment] 2016-11-28 14:12
Closing this as it is related to a very specific testing scenario involving macOS and Kafka 0.9 clients. If this problem persists, we should reopen.

**Closed by mbogoevici** 2016-11-28 14:12 UTC
