### ISSUE TITLE
Default spring boot console logging pattern corruption

### ISSUE THREAD

**Issue by e-zhydzetski** [spring-cloud/spring-cloud-stream-binder-kafka#128] opened 2017-05-03 09:40 UTC
SpringBoot: 1.5.3.RELEASE
SpringCloudStreamBinderKafka: 1.2.0.RELEASE

`KafkaBinderEnvironmentPostProcessor` breaks the default spring boot console logging pattern: https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderEnvironmentPostProcessor.java#L58

**Comment by mbogoevici** [comment] 2017-07-12 14:42
Duplicate of #133

**Closed by mbogoevici** 2017-07-12 14:42 UTC
Labels: duplicate
