### ISSUE TITLE
Allow resetting to arbitrary offsets in the Kafka binder

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#63] opened 2016-10-19 14:57 UTC
_From @mbogoevici on February 10, 2016 16:33_

As a user, I want to be able to reset the Kafka consumers to arbitrary offsets (provided that they exist) for each listened partition, so that I can replay data as needed. 

_Copied from original issue: spring-cloud/spring-cloud-stream#335_

**Comment by PedroAlvarado** [comment] 2016-10-20 17:55
Is https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/63 a duplicate of this issue?

**Comment by sabbyanandan** [comment] 2016-10-20 19:06
@PedroAlvarado: #63 is this issue itself, :). This was moved from stream project as this was specific to kafka-binder.

**Comment by PedroAlvarado** [comment] 2016-10-20 22:26
@sabbyanandan Sorry, copy/paste error on my side. I was referring to https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/20.

**Comment by schmichri** [comment] 2016-12-16 14:41
+1

**Comment by mbogoevici** [comment] 2017-07-12 13:59
Related to #34 - we should support this only when rebalancing is disabled.

@garyrussell suggests a workaround: to shutdown the app and use Kafka offset management tools to manage consumer groups/offsets between restarts.

@viniciusccarvalho suggests we consider making this a general feature for binders that support offsets.

**Comment by sobychacko** [comment] 2018-11-05 22:03
@PedroAlvarado The suggestion from @garyrussell ^^ to manage consumer offsets between restarts using the Kafka offset management tools is an ideal workaround to address this use case. Are there any pressing reasons for addressing this in the binder? I am closing this issue now. Please re-open if you still find gaps with the workarounds.

**Closed by sobychacko** 2018-11-05 22:03 UTC

**Comment by sobychacko** [comment] 2018-11-07 20:01
[This PR](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/commit/2144d3e26f4b980196633219a3cacd5e2a815a87) gives the consumer the ability to do arbitrary seek operations.
