### ISSUE TITLE
spring cloud-stream kafka disable check for kafka and zookeeper instance running on application startup

### ISSUE THREAD

**Issue by Shobhit-1309** [spring-cloud/spring-cloud-stream-binder-kafka#94] opened 2017-02-10 06:41 UTC
Hi ,

I have spring boot application, in which I configured Spring cloud stream Kafka, so when i am starting the application, on container startup it is looking for zookeeper and Kafka server running instances, if its doesn't found then it will terminate the application container.

so my requirement is I wanted a switch like thing, so i can make it configurable , so when I wanted my application to check Zookeeper and kafka instances running, I can say like true, and when I don't want I can say false, both the case I wanted my application container should start.

**Comment by artembilan** [comment] 2017-02-10 14:32
The SO on the matter http://stackoverflow.com/questions/42152909/spring-cloud-stream-kafka-disable-check-for-kafka-and-zookeeper-instance-running. And yes, from @Shobhit-1309 as well.

**Comment by mbogoevici** [comment] 2017-02-10 14:34
Closing this as a duplicate of https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/12

**Closed by mbogoevici** 2017-02-10 14:34 UTC
Labels: duplicate
