### ISSUE TITLE
spring cloud sleuth stream kafka

### ISSUE THREAD

**Issue by rujiangzhijing** [spring-cloud/spring-cloud-stream-binder-kafka#163] opened 2017-06-22 08:49 UTC
1、my spring boot cloud app config as follows:
pom.xml
`
	<dependency>
`
`
             <groupId>org.springframework.cloud</groupId>
`
`
	     <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
`
`
	</dependency>
`
`
	
`
`
	<dependency>
`
`
	     <groupId>org.springframework.cloud</groupId>
`
`
	     <artifactId>spring-cloud-starter-stream-kafka</artifactId>
`
`
	</dependency>
`
application.properties
spring.cloud.stream.kafka.binder.brokers=10.20.1.11:9092
spring.cloud.stream.kafka.binder.zkNodes=10.20.1.11:2181

2、my question
if my kafka and zookeeper is running，the spring boot app can start up ok
if i stop kafka brock，the spring boot app will start fail
so my question is:
i want to start up spring boot app well，although kafka is not running,how i can do?

**Comment by mbogoevici** [comment] 2017-07-12 14:56
Duplicate of #12

**Closed by mbogoevici** 2017-07-12 14:56 UTC
Labels: duplicate
