### ISSUE TITLE
spring-cloud-stream-binder-kafka 2.0.0.M1 can't receive event message

### ISSUE THREAD

**Issue by wiselyman** [spring-cloud/spring-cloud-stream-binder-kafka#229] opened 2017-10-16 02:50 UTC
I use `Spring Boot 2.0.0.M3` and `Spring Cloud Finchley.M2`,using `spring-cloud-stream-binder-kafka 2.0.0.M1` to test a simple produce and consume demo ,and find that produce event to `kafka` is OK, but the consumer cann't get the event message.

I change the Spring Boot version to `1.5.6.RELEASE`,Spring Cloud version to `Dalston.SR4`, everything is fine .

Demo projects link:[https://github.com/wiselyman/Spring-Cloud-Stream-Kafka-CQRS-ES](https://github.com/wiselyman/Spring-Cloud-Stream-Kafka-CQRS-ES).

Thanks for all your helps.

**Comment by a479159321** [comment] 2017-10-16 02:50
I have the same issue 
@wiselyman

**Comment by sobychacko** [comment] 2017-10-18 21:05
@wiselyman @a479159321 I am able to start and run the apps using the latest `2.0.0.BUILD-SNAPSHOT` versions. Please ensure that you don't have any dependency conflicts etc. For your reference, I created a simple sample app that contains a `source` and a `sink` here: https://github.com/sobychacko/kafka-binder-gh-229/tree/master

**Comment by a479159321** [comment] 2017-10-19 01:44
@sobychacko I have run your apps , but I still get some exceptions. I use the docker image  of `wurstmeister/kafka:0.10.2.0`, and here is the exception:

`2017-10-19 09:42:26.306 ERROR 7988 --- [ask-scheduler-1] o.s.integration.handler.LoggingHandler   : org.springframework.messaging.MessageHandlingException: error occurred in message handler [org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder$ProducerConfigurationMessageHandler@cdf89c5]; nested exception is java.lang.IllegalArgumentException: Magic v1 does not support record headers, failedMessage=GenericMessage [payload=byte[45], headers={contentType=application/json, id=8f2aee34-258d-f156-b583-4f24d3290276, timestamp=1508377346236}]
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:153)
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder$SendingHandler.handleMessageInternal(AbstractMessageChannelBinder.java:603)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:141)
	at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:116)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
	at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:105)
	at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:438)
	at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:388)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:183)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:162)
	at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)
	at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:108)
	at org.springframework.integration.endpoint.SourcePollingChannelAdapter.handleMessage(SourcePollingChannelAdapter.java:216)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint.doPoll(AbstractPollingEndpoint.java:271)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.lambda$run$0(AbstractPollingEndpoint.java:372)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:53)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.integration.util.ErrorHandlingTaskExecutor.execute(ErrorHandlingTaskExecutor.java:51)
	at org.springframework.integration.endpoint.AbstractPollingEndpoint$Poller.run(AbstractPollingEndpoint.java:366)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Magic v1 does not support record headers
	at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:385)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.appendWithOffset(MemoryRecordsBuilder.java:424)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:481)
	at org.apache.kafka.common.record.MemoryRecordsBuilder.append(MemoryRecordsBuilder.java:504)
	at org.apache.kafka.clients.producer.internals.ProducerBatch.tryAppend(ProducerBatch.java:106)
	at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:219)
	at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:747)
	at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:701)
	at org.springframework.kafka.core.DefaultKafkaProducerFactory$CloseSafeProducer.send(DefaultKafkaProducerFactory.java:247)
	at org.springframework.kafka.core.KafkaTemplate.doSend(KafkaTemplate.java:316)
	at org.springframework.kafka.core.KafkaTemplate.send(KafkaTemplate.java:190)
	at org.springframework.integration.kafka.outbound.KafkaProducerMessageHandler.handleMessageInternal(KafkaProducerMessageHandler.java:257)
	at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:141)
	... 28 more`

**Comment by artembilan** [comment] 2017-10-19 02:06
You have to use Apache Kafka `0.11.x`. That is the version supported by Spring Cloud Stream 2.0

**Comment by a479159321** [comment] 2017-10-19 04:00
@sobychacko  @artembilan  @artembilan It works! Thank you very much!

**Comment by sobychacko** [comment] 2017-10-19 21:13
@a479159321 Glad it got resolved. Closing the issue.

**Closed by sobychacko** 2017-10-19 21:13 UTC
Labels: question, ready

**Comment by qct** [comment] 2018-05-22 10:36
does it mean if I can't upgrade apache kafka broker, the only way is to use spring boot 1.5.x ?
I'm now use apache kafka 0.10.1.1 .

**Comment by garyrussell** [comment] 2018-05-22 13:22
See my reply to [your other comment](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/290#issuecomment-390942592).
