### ISSUE TITLE
Auto partition assignment issue when there are more consumers than there are partitions

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-stream-binder-kafka#41] opened 2016-09-14 20:04 UTC
_From @mnadelson on September 14, 2016 15:25_

I have a consumer that subscribes to a topic with 3 partitions.  I launch the same instance of that consumer multiple times (they will of course all have the same consumer group).  When I launch one instance the consumer gets all three partitions (as expected).  When I launch 3 instances each consumer gets one partition (as expected).  When I launch 4 instances two of the consumers got the same partition and received the same messages.  This was not expected.  I would either expect the 4th consumer to get none of the messages or the 4th consumer to round-robin the messages with the other consumer on the same partition.

_Copied from original issue: spring-cloud/spring-cloud-stream#649_

**Comment by sabbyanandan** [comment] 2016-09-14 20:04
_From @mbogoevici on September 14, 2016 18:14_

Looks like a Kafka binder issue - let's pursue this in https://github.com/spring-cloud/spring-cloud-stream-binder-kafka

**Comment by sobychacko** [comment] 2016-09-14 22:46
@mnadelson Could you give a bit more context around the issue? If you could share your configuration with us, we can try reproducing it on our end. I tried to reproduce and found that it worked as expected.

I created a simple ticktock (time | log) stream with time source writing into 3 partitions and created 4 different log-sink consumers. I found out that only 3 of them received data. When I restarted a consumer, Kafka did the auto rebalancing among partitions, i.e. only 3 of them got any partitions but reshuffled. I tried this with Kafka 0.9. 

What version of Kafka are you using?

**Comment by mnadelson** [comment] 2016-09-15 15:45
I ran my code again (and in multiple variations) and could not reproduce.  If I can I will comment back.

**Comment by sobychacko** [comment] 2016-10-07 20:24
Closing this issue because we are not able to reproduce it at this point. If we will encounter the problems described here in the future, then we will re-open this issue.

**Closed by sobychacko** 2016-10-07 20:24 UTC
Labels: bug, in progress
