### ISSUE TITLE
Consumer stops receiving messages after group rebalance

### ISSUE THREAD

**Issue by andrewtyt** [spring-cloud/spring-cloud-stream-binder-kafka#154] opened 2017-06-13 10:45 UTC
Hi,

I'm regularly facing the issue when consumer stops receiving messages after group rebalance and the only way to fix that is to restart the process. After some investigation I found that the problem seems to be connected to DLQ producer. When group rebalance happens consumer.commitSync(...) throws CommitFailedException, this exception is then passed to error handler (see [KafkaMessageListenerContainer](https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/main/java/org/springframework/kafka/listener/KafkaMessageListenerContainer.java#L518)) , and DLQ error handler fails with NPE as soon as exception has no associated message (see [KafkaMessageChannelBinder](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L293)). After that kafka-consumer thread quietly dies. With default error handler, exception is simply logged and consumer recovers processing.

Versions:
spring-cloud-stream-binder-kafka-1.1.0-RELEASE (not sure if the issue persists in later versions)
kafka-clients-0.9.0.1-cp1 (confluent platform)

Properties:
spring.cloud.stream.kafka.binder.auto-create-topics=false
spring.cloud.stream.bindings.input.destination=stream.test-input-topic
spring.cloud.stream.bindings.input.group=stream.test-group
spring.cloud.stream.bindings.output.destination=stream.test-output-topic
spring.cloud.stream.kafka.bindings.input.consumer.auto-commit-offset=true
spring.cloud.stream.kafka.bindings.input.consumer.enable-dlq=true
spring.cloud.stream.bindings.input.consumer.partitioned=true
spring.cloud.stream.bindings.input.consumer.concurrency=3
spring.cloud.stream.bindings.input.consumer.header-mode=raw
spring.cloud.stream.bindings.input.consumer.max-attempts=10
spring.cloud.stream.kafka.bindings.output.producer.sync=true
spring.cloud.stream.bindings.output.producer.header-mode=raw

Thanks!

**Comment by mbogoevici** [comment] 2017-07-12 14:54
Marking as bug. Possibly requiring a fix in Spring Kafka as well.

**Comment by sobychacko** [comment] 2017-09-06 16:42
@andrewtyt Any chance you can re-test your scenario using the latest snapshots - `1.3.0.BUILD-SNAPSHOT`? I could not reproduce the issue. However, I tried the same thing with `1.1.0.RELEASE` of the binder also and 3 consumers in the same group are consuming from the topic even after a group rebalance (with dlq settings on the consumer is enabled). So, we need to understand how exactly you were able to get that commit exception. Thank you!

**Comment by andrewtyt** [comment] 2017-09-07 13:11
@sobychacko Please take a look at this [sample](https://github.com/andrewtyt/sc_154), it simulates long-running message processing thus forcing group re-balance. 

Steps to reproduce:
1 Run the sample on any non-empty topic
2 Verify that consumer thread exists, you can simply search by name "-kafka-consumer-1" in thread dump [http://localhost:8080/dump](http://localhost:8080/dump)
3 Wait until something like "...Error XXX occurred while committing offsets..." appears in log. On my local environment it fails on 1st or 2nd message
4 Check thread dump again, there should be no consumer thread

**Comment by sobychacko** [comment] 2017-09-07 17:19
@andrewtyt Thanks for the sample. I ran it, however, my consumer was still processing messages after the error you mentioned. Here is a snippet from the log:

```
2017-09-07 13:16:49.851  INFO 76892 --- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions revoked:[sc_154.input-0]
2017-09-07 13:16:49.851 ERROR 76892 --- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Error UNKNOWN_MEMBER_ID occurred while committing offsets for group sc_154.group
2017-09-07 13:16:49.854  INFO 76892 --- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$1  : partitions assigned:[sc_154.input-0]
2017-09-07 13:16:49.856  INFO 76892 --- [afka-listener-3] sc_154.Configuration                     : Simulating long-running operation
2017-09-07 13:17:19.860  INFO 76892 --- [afka-listener-3] sc_154.Configuration                     : Simulating long-running operation
2017-09-07 13:17:49.861  INFO 76892 --- [afka-listener-3] sc_154.Configuration                     : Simulating long-running operation
.....
.....
```

**Comment by andrewtyt** [comment] 2017-09-07 20:48
@sobychacko Yes, processing goes on coz consumer thread [afka-consumer-1] fetches **batch** of messages from Kafka and another thread [afka-listener-3] processes messages from batch one by one. "Simulating long-running operation" just tells us that [afka-listener-3] thread is alive and processes rest of messages from current batch. And as I see from your logs there is no output from [afka-consumer-1] after ERROR line which means that consumer thread is actually terminated (otherwise it'd complain about re-balance) and no more messages will be fetched from Kafka.

**Comment by andrewtyt** [comment] 2017-09-08 08:16
@sobychacko I've improved [sample](https://github.com/andrewtyt/sc_154) a bit, now long-running logic is simulated for the first 5 messages only. At some point processing stops and no more messages are fetched from Kafka.

**Comment by sobychacko** [comment] 2017-09-08 15:55
@andrewtyt thanks for further explaining the issue. The only way I can reproduce this issue is by using the `Brooklyn` version of Spring Cloud Stream which uses the `0.9` Kafka client. I upgraded your sample to use `Chelsea` (and `spring boot 1.5.2` as parent) and `Ditmars.M2` (and `spring boot 1.5.6` as parent).  In both cases, I am not seeing the rebalance and the same listener thread keep consuming. Both `Chelsea` and `Ditmars` bring in the `0.10` kafka client and spring kafka 1.1.x. 

Is upgrading to either `Chelsea` or `Ditmars` an option for you? `Ditmars` will be generally available before the end of this month. 

Here is the log output from your sample using the Chelsea version:

```
2017-09-08 11:33:05.577  INFO 94909 --- [afka-consumer-1] o.a.k.c.c.internals.ConsumerCoordinator  : Setting newly assigned partitions [sc_154.input-0] for group sc_154.group
2017-09-08 11:33:05.591  INFO 94909 --- [afka-consumer-1] o.s.c.s.b.k.KafkaMessageChannelBinder$3  : partitions assigned:[sc_154.input-0]
2017-09-08 11:33:05.611  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:33:36.063  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:34:06.068  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:34:36.073  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:35:06.079  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:35:36.084  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:36:06.087  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:36:36.093  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:37:06.098  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:37:36.105  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:38:06.110  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:38:36.115  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:39:06.120  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:39:36.124  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:40:06.128  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:40:36.136  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:41:06.140  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:41:36.144  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:42:06.148  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:42:36.156  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:43:06.163  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:43:36.167  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:44:06.173  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:44:36.180  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:45:06.182  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:45:36.188  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:46:06.194  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:46:36.198  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:47:06.203  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:47:36.208  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
2017-09-08 11:48:06.213  INFO 94909 --- [afka-listener-1] sc_154.Configuration                     : Simulating long-running operation
......
......
......
```

**Comment by andrewtyt** [comment] 2017-09-11 08:30
@sobychacko Currently we're using Kafka server `0.9` on production so in our case upgrade to later version of Spring Cloud Stream in our applications is only possible with downgrade to `0.9` Kafka client. I've tested `Chelsea` + Kafka client `0.9` and the issue is still reproducible...
Anyway I guess the issue can be closed. As workaround we've disabled DLQ functionality and are planing migration to Kafka `0.11`.
Thank you.

**Comment by sobychacko** [comment] 2017-09-11 13:49
@andrewtyt `0.9` client will have this problem and using `Chelsea` with `0.9` client won't help. Will close the issue for the time being as this doesn't happen with `0.10` clients and later `Scst` versions. Please report if you see the same problems there. Thank you for the valuable suggestions above!

**Comment by sobychacko** [comment] 2017-09-11 16:50
Closing the issue as the general recommendation is to upgrade to a 0.10 (or above) client.

**Closed by sobychacko** 2017-09-11 16:50 UTC
Labels: bug, in progress
