### ISSUE TITLE
EmbeddedKafka for KafkaStreams Integration testing

### ISSUE THREAD

**Issue by en-vee** [spring-cloud/spring-cloud-stream-binder-kafka#1057] opened 2021-03-31 07:39 UTC
Hi,
I have a spring cloud stream kafka streams application using Kafka 2.7.
I am trying to setup an integration test to test my Functional Beans (KStream<K,V>,KStream<K,V>).

The function definition bean gets invoked, but the topology that the bean creates never gets invoked:

Bean in the ```@Component``` class which returns a Function<KStream,KStream> and this is bound to input/output topics via application.yml.
If I run an Junit test using EmbeddedKafka, the debugger does enter this method.

```java
@Bean
	public Function<KStream<String,ChargingEvent>, KStream<String,AggregatedOutputRecord>> dataAggregator() {
				
		Function<KStream<String, ChargingEvent>, KStream<String,AggregatedOutputRecord>> aggregationFunction = this.contextBasedAggregation;
		...	
		...
		return aggregationFunction ;
	}
```

The contextBasedAggregation Function in the same Component class
```java
private Function<KStream<String,ChargingEvent>, KStream<String,AggregatedOutputRecord>> contextBasedAggregation = 
			(inputStream) -> {
				return inputStream.filter(isValidChargingEvent)
						.filter((k,v)->v != null)
						.transformValues(() -> new SessionBasedDataUsageAccumulator(this.applicationProperties.getGlobalSettings().getChargingInformationAdditionMode()), Constants.STORE_NAME)
						.filter((k,v)->v != null)
						.flatMapValues(splitById)
						.filter(isThresholdBreached)
						.mapValues(mapToList)						
						.mapValues(toOutputRecord)
						.transformValues(() -> new DataSessionAggregatedRecordResetter(AggregationMode.CONTEXT_LEVEL, sessionReleaseAggregationEnabled),Constants.STORE_NAME)
						.mapValues(v -> {
							if(v.getAggregations().size() == 0) {
								return v;
							}
							Integer ratingGroupId = v.getAggregations().get(0).getRatingGroupId();
							v.dropMuuElementsOtherThanRatingGroup(ratingGroupId);
							return v;
						})
						;
			};
```

As seen above, there are a couple of transformers being used, but they just don't get invoked.

My test class contains a Driver class which is basically my SpringBootApplication containing the ```main()``` method :
```java
@EmbeddedKafka(
		topics = {EmbeddedKafkaBrokerTests.INPUT_TOPIC_NAME, EmbeddedKafkaBrokerTests.OUTPUT_TOPIC_NAME})
@DirtiesContext
class EmbeddedKafkaBrokerTests {
	
	String sunnyDayJson = "{\"x\": 1234}";
	
	static final String INPUT_TOPIC_NAME = "input-topic";
	static final String OUTPUT_TOPIC_NAME = "output-topic";
	private static final String CONSUMER_GROUP_NAME = "test-cg";
	private static KafkaTemplate<String, ChargingEvent> kafkaTemplate;
	private static ConsumerFactory<String, AggregatedOutputRecord> consumerFactory;
	private static Consumer<String, AggregatedOutputRecord> consumer;
	private static ConfigurableApplicationContext context;
	
	@BeforeAll
	static void setUpBeforeClass(EmbeddedKafkaBroker embeddedKafka) throws Exception {
		// Producer Properties
		Map<String,Object> producerProps = new HashMap<>();
		producerProps.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, embeddedKafka.getBrokersAsString());
		producerProps.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
		producerProps.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);
		DefaultKafkaProducerFactory<String, ChargingEvent> producerFactory = new DefaultKafkaProducerFactory<>(producerProps);
		kafkaTemplate = new KafkaTemplate<>(producerFactory,true);
		
		// Consumer Properties
		Map<String,Object> consumerProps = KafkaTestUtils.consumerProps(CONSUMER_GROUP_NAME, "true", embeddedKafka);
				
        consumerProps.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class );
        consumerProps.put(ConsumerConfig.CLIENT_ID_CONFIG, "test");
        consumerProps.put(ConsumerConfig.AUTO_COMMIT_INTERVAL_MS_CONFIG, 1000);
        consumerProps.put(JsonDeserializer.TRUSTED_PACKAGES, EmbeddedKafkaBrokerTests.class.getPackage().getName());
        consumerProps.put(JsonDeserializer.KEY_DEFAULT_TYPE, String.class);
        consumerProps.put(JsonDeserializer.VALUE_DEFAULT_TYPE, AggregatedOutputRecord.class);
        consumerProps.put(JsonDeserializer.USE_TYPE_INFO_HEADERS, "false");
        consumerFactory = new DefaultKafkaConsumerFactory<>(consumerProps);
        consumer = consumerFactory.createConsumer(CONSUMER_GROUP_NAME);
        consumer.subscribe(Collections.singleton(OUTPUT_TOPIC_NAME));
                
        context = new SpringApplicationBuilder(Driver.class)
                .properties(
                        "spring.cloud.stream.kafka.streams.binder.brokers=" + embeddedKafka.getBrokersAsString(),
                        "spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms=1000",
                        "spring.cloud.stream.kafka.streams.binder.configuration.cache.max.bytes.buffering=0")
                .run();
                
	}

	@AfterAll
	static void tearDownAfterClass() throws Exception {
		context.close();
	}

	@BeforeEach
	void setUp() throws Exception {
		
	}

	@AfterEach
	void tearDown() throws Exception {
	}

	@Test
	void test() {
		// First Produce a message to the INPUT_TOPIC
		ChargingEvent ce = new ChargingEvent();
		Request request = new Request();
		request.setOperationName(OperationName.Nchf_ConvergedCharging_Update);
		ce.setRequest(request);
		ChargingDataRequest cdr = null;
		try {
			cdr = ChargingDataRequest.from(sunnyDayJson);
			cdr.setInvocationSequenceNumber(0);
			request.setBody(cdr);
		} catch (DeserializationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		kafkaTemplate.send(INPUT_TOPIC_NAME, ce);
		cdr.setInvocationSequenceNumber(1);
		kafkaTemplate.send(INPUT_TOPIC_NAME, ce);
		cdr.setInvocationSequenceNumber(2);
		kafkaTemplate.send(INPUT_TOPIC_NAME, ce);
		
		kafkaTemplate.flush();
		// Consume the aggregated event
		ConsumerRecords<String, AggregatedOutputRecord> consumerRecords = KafkaTestUtils.getRecords(consumer, 5000);
		System.out.println(consumerRecords.count());
	}

}

```

**Comment by en-vee** [comment] 2021-03-31 07:41
Basically, if I set breakpoints in the ```transform``` method of the class ```SessionBasedDataUsageAccumulator```, they don't get hit when I run the test case above.

**Comment by sobychacko** [comment] 2021-03-31 14:18
Not sure what the issue is, but here is an application with tests written almost in the same way as your setup: https://github.com/spring-cloud/spring-cloud-stream-samples/tree/master/kafka-streams-samples/kafka-streams-inventory-count

You might want to compare notes to see where it differs from your test setup. If it still doesn't work after that, please share a reproducible sample and we can then triage it further.

**Comment by en-vee** [comment] 2021-04-01 01:16
Thanks for your inputs @sobychacko 
I'll have a look at that example.

**Comment by en-vee** [comment] 2021-04-01 20:27
I seem to have overcome my issue of not being able to hit the breakpoint in my custom ```transformer``` code.
Everytime, I kept seeing the following messages in the log when my test case was being setup.
```
2021-04-02 07:16:48,464 ERROR [data-plane] k.s.KafkaApis:74 - [KafkaApi-0] Number of alive brokers '1' does not meet the required replication factor '3'
```

So, I added increased the number of brokers to 3 in my ```EmbeddedKafka``` annotation to my Test class via :
```
@EmbeddedKafka(
		topics = EmbeddedKafkaBrokerTests.INPUT_TOPIC_NAME,
		count = 3
		)
```

This helped the error message (mentioned above) in the log to go away and also caused my custom ```transformer``` code to get executed.

However, the  (inventory-count) samples which @sobychacko pointed me to do not seem to exhibit this issue.

Any suggestions on why this is not happening for the the spring-cloud-stream samples which @sobychacko pointed me to ?

Or rather why I am being forced to specify the number of brokers in the embedded kafka annotation ?

My build.gradle is as follows :
```groovy
plugins {
	id 'org.springframework.boot' version '2.4.2'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id "nebula.ospackage" version "8.5.6"
}

group = 'com.company'

ext {
	rpmVersion='0.0.1'
}

sourceCompatibility = '1.11'

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

ext {
	set('kafkaVersion',"2.6.0")
	set('springKafkaVersion',"2.6.7")
	set('springCloudVersion', "2020.0.0")
}

dependencies {

	implementation project(':common')
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	

	implementation "org.springframework.kafka:spring-kafka"
	implementation "org.apache.kafka:kafka-streams"

	
	implementation 'org.springframework.cloud:spring-cloud-stream'
	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka'
	implementation 'org.springframework.cloud:spring-cloud-stream-binder-kafka-streams'
	
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation "org.springframework.kafka:spring-kafka-test"
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}
```

**Comment by garyrussell** [comment] 2021-04-01 20:42
If you are using transactions, the state logs require 3 brokers by default, you can change that, as the core Spring for Apache Kafka project does in some of its tests.

https://github.com/spring-projects/spring-kafka/blob/master/spring-kafka/src/test/java/org/springframework/kafka/listener/TransactionalContainerTests.java#L119

**Comment by sobychacko** [comment] 2021-09-30 22:33
@en-vee Hoping that you got around to this problem. Closing the issue now. Please feel free to re-open if you see any further issues.

**Closed by sobychacko** 2021-09-30 22:33 UTC
