### ISSUE TITLE
Kafka metrics not appearing on Actuator 

### ISSUE THREAD

**Issue by lawhiteley** [spring-cloud/spring-cloud-stream-binder-kafka#498] opened 2018-11-16 11:37 UTC
Hi,

We're trying to expose our Kafka binder's metrics using Actuator but they don't seem to be appearing. Based on the documentation, we expected `spring.cloud.stream.binder.kafka.offset` to appear in the names array on the `/actuator/metrics` endpoint with details at `/actuator/metrics/spring.cloud.stream.binder.kafka.offset`. We're using version `2.1.0.RELEASE` of Spring Boot and Actuator as well as version `1.1.0` of Micrometer. Our binding is appearing at `/actuator/bindings`. 

Our `application.yml` contains the following: 

```
management:
  endpoints:
    web:
      exposure:
        include: bindings, metrics, health
```

Happy to supply any more information if required.

Thanks

**Comment by mark-r-m** [comment] 2018-11-16 12:55
We've been through the note as found in the page give above by @lawhiteley,  these pages, but nothing has worked:
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka#kafka-metrics
* https://stackoverflow.com/questions/52764233/spring-cloud-kafka-streams-binder-offset-metrics
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/blob/master/spring-cloud-stream-binder-kafka/src/test/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetricsTest.java
* https://spring.io/blog/2018/04/10/announcing-general-availability-of-spring-cloud-stream-elmhurst-release-2-0-0-release#micrometer-support 
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/250
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/318
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/320
* https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/321

**Comment by sobychacko** [comment] 2018-11-29 21:09
@lawhiteley @mark-r-m Aplogies for the delay. I just ran a sample application with Boot `2.1.0.RELEASE` and Spring Cloud Stream `Fishtown` snapshot, micrometer `1.1.0.RELEASE` etc.

I am actually getting the metrics. See below.

`actuator/metrics`

```
{"names":[,"spring.cloud.stream.binder.kafka.offset","kafka.consumer.join.rate",
"jvm.threads.states","kafka.consumer.commit.rate",
"kafka.consumer.io-wait-time-avg","kafka.consumer.heartbeat.rate",
"kafka.consumer.select.total","..............]}
```

and `actuator/metrics/spring.cloud.stream.binder.kafka.offset`

```
{"name":"spring.cloud.stream.binder.kafka.offset",
"description":"Unconsumed messages for a particular group and topic","baseUnit":null,"measurements":
[{"statistic":"VALUE","value":5.0}],"availableTags":
[{"tag":"topic","values":["kafka-binder-gh-498"]},
{"tag":"group","values":["anonymous.5fff7127-3efa-4dd7-9b4c-d4c49a04fd95"]}]}
```

If you can provide a small sample app where it fails for you, we can troubleshoot it further.

**Comment by mark-r-m** [comment] 2018-11-29 23:18
Awesome, we will try it!

Cheers,
Mark Matthews,
ARKM Enterprises Ltd
----------------------------------------

________________________________

**Comment by mark-r-m** [comment] 2018-12-05 14:35
I tried and failed to get the metrics :-(
We've a card to try again in this spring, we will let you know :-)

Cheers,
Mark Matthews,
ARKM Enterprises Ltd
----------------------------------------

________________________________

**Comment by sobychacko** [comment] 2018-12-05 15:31
@mark-r-m If it doesn't work, please provide a small application where it fails and include instructions to reproduce.

**Comment by ennala** [comment] 2019-02-12 01:05
@sobychacko I am facing a similar issue where i am not able to see this metric in my actuator/metrics end point.

These are the versions which I am using:

Spring Boot: 2.1.2.RELEASE
Micrometer: 1.1.2 Also tried with 1.1.0 version.
Spring cloud streams: 2.1.0.RELEASE

I am able to see my binders in actuator/bindings and I am able to see a lot of kafka metrics in the metrics end point except this one spring.cloud.stream.binder.*

Not sure if this a bug.
Appreciate your help.

**Comment by sobychacko** [comment] 2019-02-12 01:38
@ennala Did you try these endpoints mentioned on this [comment](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/498#issuecomment-442993846)? I will check to see if there is any issues, but as far as I can tell, it should work.

**Comment by ennala** [comment] 2019-02-12 01:41
@sobychacko yes I did try that. Its not showing in the metrics end point to start with.

**Comment by sobychacko** [comment] 2019-02-12 02:03
@ennala This worked for me on a new app with the same dependency as you have. 
`actuator/metrics/spring.cloud.stream.binder.kafka.offset` 

Response:

```
{"name":"spring.cloud.stream.binder.kafka.offset","description":"Unconsumed messages for a particular group and topic","baseUnit":null,"measurements":[{"statistic":"VALUE","value":0.0}],"availableTags":[{"tag":"topic","values":["input"]},{"tag":"group","values":["anonymous.053e259d-2d0f-4680-89a1-705d3d92f0f9"]}]}
```
Do you get any response from the request?

**Comment by ennala** [comment] 2019-02-12 03:01
@sobychacko I am able to reproduce with this config when we specify the binders.

`spring.cloud.stream:
      bindings:
        inbound:
          destination: testInputTopic
          binder: inbound
          group: testGroup
          consumer:
            concurrency: 5
            max-attempts: 3
            backOffInitialInterval: 3000
            backOffMaxInterval: 30000
            backOffMultiplier: 2
            partitioned: true
        outbound:
          destination: testOutputTopic
          binder: outbound
      binders:
        inbound:
          type: kafka
          defaultCandidate: false
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9092
        outbound:
          type: kafka
          environment.spring.cloud.stream.kafka.binder:
            brokers: localhost:9092`

Its reporting properly when binders are not specified.

`spring.cloud.stream:
      bindings:
        inbound:
          destination: testInputTopic
          group: testGroup
          consumer:
            concurrency: 5
            max-attempts: 3
            backOffInitialInterval: 3000
            backOffMaxInterval: 30000
            backOffMultiplier: 2
            partitioned: true
        outbound:
          destination: testOutputTopic`

Let me know if are you able to reproduce it or if you want to me provide more information.

**Comment by sabbyanandan** [comment] 2019-02-12 15:49
Thanks. We will have a look in the latest release.

**Comment by sobychacko** [comment] 2019-02-12 21:32
@ennala Looks like we have an issue when we have multi binders as you have in the configuration. 
I will close this issue and create a new one to track it.

**Comment by sobychacko** [comment] 2019-02-12 21:33
[New issue created](https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/546) for tracking metrics issues with a multi-binder configuration.

**Closed by sobychacko** 2019-02-12 21:33 UTC
Labels: question, ready

**Comment by ennala** [comment] 2019-02-12 23:07
Thanks @sobychacko @sabbyanandan
