### ISSUE TITLE
Kafka consumer property 'resetOffsets' has no effect

### ISSUE THREAD

**Issue by cmuelhau** [spring-cloud/spring-cloud-stream-binder-kafka#67] opened 2016-11-01 10:54 UTC
While creating a consumer (and setting group id), the property `spring.cloud.stream.kafka.bindings.<channelName>.consumer.resetOffsets` (as described here: http://docs.spring.io/spring-cloud-stream/docs/Brooklyn.RELEASE/reference/htmlsingle/#_kafka_consumer_properties) seems to have no effect, and consumer consumes from last offset.
Sample properties:
```yaml
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: topic
          group: sample_group
      kafka:
        bindings:
          input:
            consumer:
              resetOffsets: true
              startOffset: earliest
```
The `KafkaConsumerProperties#resetOffsets` extension is set to true, but it doesn't seem to trigger any specific resetting of offsets.

**Comment by mbogoevici** [comment] 2016-11-01 11:55
Hi @cmuelhau,

We have another open issue for this: #63 . This is an feature loss that has been introduced by the adoption of the new Kafka client with rebalancing support (we should update documentation to reflect that). Implementation-wise this is a problem when auto-rebalance with multiple instances comes into play, as multiple arriving instances may reset multiple times without the proper coordination. We are currently deciding whether to officially drop this feature or support it only when auto-rebalancing is disabled (partition allocation is static based on `index`/`instanceCount` like in 1.0). 

In the mean time, a solution for this would be to use a new group name when rebalance is required, which would effectively force the consumer to reset.  

Really looking for the best suggestion here, as we'd really want to be able to support this, but we're also aware that we should do so in a manner that works properly.

Thank you for the interest!

**Comment by dvsridhar** [comment] 2017-03-24 20:05
We use Brookly.Release cloud stream version and I wish this feature works. We have a unique use case that requires old pub/sub model. i.e. subscribers only wants to receive when they are alive. 

Our use case is on the lines of raw-sensor-data consumer group example but the consumer group instance only needs to receive latest messages, in other words when a consumer group instance goes down and comes back up it doesn't want to pick up the missed messages. 

spring.cloud.stream.kafka.bindings.schedulerTestInput.consumer.resetOffsets=true
spring.cloud.stream.kafka.bindings.schedulerTestInput.consumer.startOffset=latest

The above setting has no effect on our consumer behavior it always picks messages from consumer group last successful commit.

**Comment by mbogoevici** [comment] 2017-03-24 20:10
@dvsridhar Using an anonymous consumer group should pick up only the latest updates.

**Comment by dvsridhar** [comment] 2017-03-24 20:18
Thank you very much for the quick update.
spring.cloud.stream.bindings.schedulerTestInput.group=anonymous

Are you referring to the above setting? If so if I have multiple consumer groups can i use the same group name 'anonymous' for all consumer groups.

**Comment by mbogoevici** [comment] 2017-03-24 20:21
Sorry, that wasn't too clear :). Simply not using a group name for your application will make it an anonymous consumer. The only case where this is problematic is when you have multiple instances (and they will all be anonymous consumers).

**Comment by dvsridhar** [comment] 2017-03-24 20:27
I am testing as we speak. But yeah i do have multiple consumer groups of the topic (multi partitioned) and each consumer group will have multiple micro services to consume multi partitioned data. Are you saying this will be a problem use case.

**Comment by dvsridhar** [comment] 2017-03-24 20:31
I used the following configuration.
===========================
spring.cloud.stream.bindings.schedulerTestInput.destination=${scheduledJobExecutionRequest.topic.name}
spring.cloud.stream.bindings.schedulerTestInput.content-type=${garnet.kafka.content-type}
spring.cloud.stream.bindings.schedulerTestInput.consumer.partitioned=true
spring.cloud.stream.bindings.schedulerTestInput.consumer.maxAttempts=${garnet.consumer.default.maxAttempts}
spring.cloud.stream.bindings.schedulerTestInput.consumer.backOffInitialInterval=${garnet.consumer.default.backOffInitialInterval}
spring.cloud.stream.bindings.schedulerTestInput.consumer.backOffMaxInterval=${garnet.consumer.default.backOffMaxInterval}
spring.cloud.stream.bindings.schedulerTestInput.consumer.backOffMultiplier=${garnet.consumer.default.backOffMultiplier}
spring.cloud.stream.kafka.bindings.schedulerTestInput.consumer.autoRebalanceEnabled=true

Looks like i need to give the consumer group. It is throwing an error saying  'A consumer group is required for a partitioned subscription'.

Error.
======================
{"mdc": {}, "debug_level":"ERROR","debug_timestamp":"2017-03-24 20:28:01,683","debug_thread":"main","debug_file":"SpringApplication.java", "debug_line":"839","debug_message":"Application startup failed"}
org.springframework.context.ApplicationContextException: Failed to start bean 'inputBindingLifecycle'; nested exception is java.lang.IllegalArgumentException: A consumer group is required for a partitioned subscription
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:176)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:51)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:346)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:149)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:112)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:874)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:761)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:371)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1186)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1175)
	at com.cgi.garnet.Application.main(Application.java:14)
Caused by: java.lang.IllegalArgumentException: A consumer group is required for a partitioned subscription
	at org.springframework.util.Assert.isTrue(Assert.java:68)
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:138)
	at org.springframework.cloud.stream.binding.ChannelBindingService.bindConsumer(ChannelBindingService.java:93)
	at org.springframework.cloud.stream.binding.BindableProxyFactory.bindInputs(BindableProxyFactory.java:191)
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:55)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:173)
	... 14 more

**Comment by mbogoevici** [comment] 2017-03-24 20:32
Yes, multiple instances that are anonymous consumers will consume the same set of messages. Unfortunately, rebalancing makes it impossible to reliably reset offsets on the consumer side. That being said, offsets stored in Kafka can always be deleted using their tools.

**Comment by mbogoevici** [comment] 2017-03-24 20:35
As of Brooklyn, you don't need to specify `spring.cloud.stream.bindings.schedulerTestInput.consumer.partitioned=true` anymore. But see my comment above multiple instances.

**Comment by dvsridhar** [comment] 2017-03-24 20:45
Yeah once i removed the partitioned true configuration, microservices started fine But I do get your point on the multiple instances and unfortunately we will be using multiple instances. So we have to look for alternatives. Thank you very much for all the help.

**Comment by mbogoevici** [comment] 2017-03-24 20:50
No problem. There is another specific when we could in principle support this, using named groups:  rebalancing can be suppressed in the clients using `autoRebalanceEnable=false` - see http://docs.spring.io/autorepo/docs/spring-cloud-stream-docs/Brooklyn.BUILD-SNAPSHOT/reference/htmlsingle/#_kafka_consumer_properties. In those cases the behaviour on start (or restart) is deterministic enough so that we can consider supporting offsets. We've thought about this for a while - happy to get some feedback here.

**Comment by dvsridhar** [comment] 2017-03-24 21:34
autoRebalanceEnable=false put lot of onus the devops to manage the static partitioning of microservice instances. If a microservice needs a state full behavior that's when static partitioning or  autoRebalanceEnable=false make sense, otherwise 99% of our microservice implementations are stateless and Spring Cloud stream brooklyn version support for 0.9 consumer was very well appreciated. Thank you very much for all the hard work on this :).

So in my case, the micro service that is consuming central topic messages deals with several other kafka topics which requires auto re-balance true, so in this scenario providing support on autoRebalanceEnable=false may not help as this requires devops to pass the instanceIndex and instanceCount as JVM params and this will effect other topics as all the topics are not equally partitioned.

However, this feature may be useful where a developer doesn't need to deal with different kind of topics, but not sure how often that will be useful especially in microservice use case where it needs to deal several tell scenarios.

**Comment by javyzheng** [comment] 2017-05-25 08:26
@mbogoevici I went through the discussion and wonder how the `resetOffsets=true` works in my case.

I have **4 instances of the same consumer**(4 partitions in the related topic) in a **named group**. What will happen if I restart the consumer with the following configuration?

```
resetOffsets: true
startOffset: earliest
autoRebalanceEnable=true
```

**Comment by mbogoevici** [comment] 2017-05-25 10:15
@javyzheng 

Multiple applications starting or (re)starting together are likely to undergo a rebalancing process as their consumer groups will connect. 
Depends on the timing, what you will see is the first instance receiving all partitions, then rebalance a partition subset as the consumer group is expanding, until last instance arrives.  I would suggest you try it out and follow the logs.

**Comment by mbogoevici** [comment] 2017-07-12 14:22
Moving this to later on. 

Our suggested workaround is to manage offsets using the Kafka consumer group management CLI tooling (http://kafka.apache.org/0102/documentation.html#basic_ops_consumer_group)  between application restarts. (Also set the `startOffset` to `earliest` or `latest` so that the application can restart at the proper offset).

**Comment by garyrussell** [comment] 2018-03-04 20:48
We should be able to reinstate this by seeking to the topic/partition during startup.

**Closed** 2018-03-06 01:51 UTC
Labels: in pr
