### ISSUE TITLE
Kafka partitions do not get created if relaunching a stream

### ISSUE THREAD

**Issue by mshalak-nix** [spring-cloud/spring-cloud-stream-binder-kafka#819] opened 2019-12-13 10:15 UTC
I use Kubernetes and Kafka. When I create a stream with starters (trigger->log) and specify 3 instances of a log sink, underneath Kafka topic is created with 3 partitions, so load balancing works fine. When I stop the stream and relaunch it with 4 instances of a log sink, Kafka topic remains the same, which means the 4th pod will not receive messages since there are still only 3 partitions.
Is this a bug, or some additional configuration required?

**Comment by sobychacko** [comment] 2019-12-16 17:02
@mshalak-nix I think what you are observing is the expected behavior. After a new topic is created by the binder provisioner, it won't increase the existing partitions count unless you enable the configuration:  `spring.cloud.stream.kafka.binder.autoAddPartitions: true`. By default, this property is disabled and you have to explicitly enable this.

**Comment by mshalak-nix** [comment] 2019-12-16 21:32
Thanks for reply. Can this be configured for a SCDF server itself, or for a separate stream application? If the second, I guess this will not work if I use a Python based application inside a container, not a Spring based one.

**Comment by sobychacko** [comment] 2019-12-17 02:15
This is a binder level property that needs to be set on the application. Did you take a look [here](https://dataflow.spring.io/docs/recipes/polyglot/app/)?

**Comment by sobychacko** [comment] 2019-12-17 15:04
For the external python app, its the responsibility of the application to define the topic/partitions.

**Comment by mshalak-nix** [comment] 2019-12-17 17:24
Thanks, was able to get around this by introducing the following code into the Python container startup script, improved code provided in https://dataflow.spring.io/docs/recipes/polyglot/processor/ . Using arguments passed by SCDF server to get a broker URL, topic name, number of instances:
```
admin_client = KafkaAdminClient(bootstrap_servers=[get_kafka_binder_brokers()], client_id=sys.argv[0])

partition_count = get_cmd_arg("spring.cloud.stream.instanceCount")

# create Kafka topic if does not exist
new_topic = NewTopic(name=get_input_channel(), num_partitions=partition_count, replication_factor=1)
try:
    admin_client.create_topics(new_topics=[new_topic])
except TopicAlreadyExistsError:
    logging.info(f"Topic {get_input_channel()} was already created")

# add Kafka partitions to existing topic
new_partitions = NewPartitions(total_count=partition_count)
try:
    admin_client.create_partitions(topic_partitions={get_input_channel(): new_partitions})
except InvalidPartitionsError as exp:
    logging.info(f"No need to increase Kafka partitions for topic {get_input_channel()}")
```

**Comment by sabbyanandan** [comment] 2019-12-17 18:27
Thanks for the update, @mshalak-nix. Since we already discussed it in StackOverflow, I will close it here.

**Closed by sabbyanandan** 2019-12-17 18:27 UTC
