### ISSUE TITLE
Number of expected partitions mismatch

### ISSUE THREAD

**Issue by YossiShasha** [spring-cloud/spring-cloud-stream-binder-kafka#230] opened 2017-10-16 11:42 UTC
Scenario:
1. Kafka has a certain topic with 3 partitions.
2. I'm booting a service that produces to this partitions and the configured partition count is 100 (of course with autoAddPartitions = true).
3. The following exception is raised:

`java.lang.IllegalStateException: The number of expected partitions was: 100, but 3 have been found instead at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner$2.doWithRetry(KafkaTopicProvisioner.java:260) ~[spring-cloud-stream-binder-kafka-core-1.2.1.RELEASE.jar!/:1.2.1.RELEASE] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner$2.doWithRetry(KafkaTopicProvisioner.java:246) ~[spring-cloud-stream-binder-kafka-core-1.2.1.RELEASE.jar!/:1.2.1.RELEASE] at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:286) ~[spring-retry-1.2.0.RELEASE.jar!/:na] at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:163) ~[spring-retry-1.2.0.RELEASE.jar!/:na] at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.getPartitionsForTopic(KafkaTopicProvisioner.java:246) ~[spring-cloud-stream-binder-kafka-core-1.2.1.RELEASE.jar!/:1.2.1.RELEASE] at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:149) [spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar!/:1.2.1.RELEASE] at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createProducerMessageHandler(KafkaMessageChannelBinder.java:88) [spring-cloud-stream-binder-kafka-1.2.1.RELEASE.jar!/:1.2.1.RELEASE] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:112) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindProducer(AbstractMessageChannelBinder.java:57) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.cloud.stream.binder.AbstractBinder.bindProducer(AbstractBinder.java:152) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.cloud.stream.binding.BindingService.bindProducer(BindingService.java:124) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.cloud.stream.binding.BindableProxyFactory.bindOutputs(BindableProxyFactory.java:238) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.cloud.stream.binding.OutputBindingLifecycle.start(OutputBindingLifecycle.java:57) [spring-cloud-stream-1.2.2.RELEASE.jar!/:1.2.2.RELEASE] at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:175) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:50) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:348) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:151) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE] at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:114) [spring-context-4.3.7.RELEASE.jar!/:4.3.7.RELEASE]`

4. Even though the service failed to start,  when I executed ./kafka-topics.sh --describe --zookeeper zookeeper:2181 --topic my-topic, the number of partitions that returned is 100.

Some notes: 
1. When I was trying the same scenario but with 6 partitions and not 100 this hasn't happened and the service had started successfully.
2. After waiting for about 10 minutes in debugging the fact that the code that generated the exception is wrapped inside a RetryTemplate this exception wasn't raised again (I saw that the instance of the partitonByTopic field that is inside the Cluster object has changed and included the new partition infos).

**Comment by sobychacko** [comment] 2017-10-16 17:29
@YossiShasha The fact that you saw this exception thrown when the number of partitions were 100 and didn't see this when it was 6 could be an indication that there might be some timing (asynchronous) issues hiding there. The call to increase partitions happens before you come to this `getPartitionsForTopic` check (where you got the above exception) and since the partition count is larger, it still hasn't finished adding all the partitions. Looks like a bug. We will do further investigation.

**Comment by YossiShasha** [comment] 2017-10-17 08:58
OK, that's exactly what I suspected.

**Comment by sobychacko** [comment] 2017-10-19 22:19
@YossiShasha What version of Kafka are you running? I am unable to reproduce the scenario that you described using the latest `spring-cloud-stream` and `binder` snapshots and Kafka version `0.11.0.1`. Any chance you can test on the latest and confirm if you still see this same behavior?

**Comment by YossiShasha** [comment] 2017-10-20 05:22
@sobychacko Sure, but I will only be able to try it on Sunday.

**Comment by YossiShasha** [comment] 2017-10-22 13:28
Good news :)
Although I wasn't able to try to reproduce the error with the latest versions due dependencies problems,
I was able to run it on `spring-cloud-stream Ditmars` which uses `spring-cloud-stream-binder-kafka 1.3.0.REALEASE` (previously I used `spring-cloud-stream Chelsea SR2` and  `spring-cloud-stream-binder-kafka 1.2.1.REALEASE`). With the new versions the error wasn't reproduced and I also think that I know the reason:
The method createProducerMessageHandler in KafkaMessageChannelBinder in `spring-cloud-stream-binder-kafka 1.3.0.REALEASE` has changed and now in the end of each invocation of the call() method you close the producer and destroy the producerFB instances. By doing this in the next time that the method createProducer is called and a new Producer instance is created. In one of the subsequent invocations the Metadata inside the Producer contains the updated Cluster info.

**Comment by sobychacko** [comment] 2017-10-23 13:25
Thank you @YossiShasha for the confirmation. Glad it worked for you with the latest release. I am closing this issue based on your findings and analysis.

**Closed by sobychacko** 2017-10-23 13:25 UTC
Labels: bug, ready

**Comment by Pavithra2001** [comment] 2021-09-23 06:19
Hi. I am getting similar problem. 
I am using embedded kafka to test my kafka consumer. I have used KafkaMessageListenerContainer. The tests passed in my local however it fails in the CI pipeline with the following error
java.lang.IllegalStateException: Expected 1 but got 0 partitions.

I have referred: https://blog.mimacom.com/testing-apache-kafka-with-spring-boot-junit5/ for the code
