### ISSUE TITLE
Unused parameter log messages when health endpoint is called

### ISSUE THREAD

**Issue by tschuettel** [spring-cloud/spring-cloud-stream-binder-kafka#155] opened 2017-06-15 16:11 UTC
I upgraded to the latest Spring Cloud Dalston.SR1 release train. Whenever the health endpoint is called on the microservices I see the following warnings:

o.a.k.clients.producer.ProducerConfig    : The configuration 'key.deserializer' was supplied but isn't a known config.
o.a.k.clients.producer.ProducerConfig    : The configuration 'value.deserializer' was supplied but isn't a nown config.

o.a.k.clients.consumer.ConsumerConfig    : The configuration 'value.serializer' was supplied but isn't a known config.
o.a.k.clients.consumer.ConsumerConfig    : The configuration 'key.serializer' was supplied but isn't a known config.

After digging into the code, I found in class org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration the inner class KafkaPropertiesConfiguration which adds the consumer and producer default properties to KafkaBinderConfigurationProperties. Since this list contains the serializer properties for consumer and producer the unused properties check in Apache Kafka client reports the above messages as warnings.

Please advice.

**Comment by TabberGit** [comment] 2017-06-15 16:20
This is directly related to the issue I opened a while back in #142, but hasn't been picked up, yet.

**Comment by rotilho** [comment] 2017-06-16 08:27
I had also mentioned it here #123 however I didn't have time to take a look in the root cause since then.

**Comment by tschuettel** [comment] 2017-06-16 10:46
I reviewed the code again and I cannot really understand why the inner class KafkaPropertiesConfiguration was added in org.springframework.cloud.stream.binder.kafka.config.KafkaBinderConfiguration.
The default consumer and producer properties are added anyway when creating a consumer or producer.
Maybe someone from the core developer team can comment on this.

**Comment by mbogoevici** [comment] 2017-06-16 13:45
@tschuettel That class captures the Spring Boot properties for Kafka - we are not using the autoconfiguration, because we create one ConsumerFactory/ProducerFactory per binding (they have different properties). The class also deals with the fact that in version 1.2.x we need to support both Boot 1.5 and Boot 1.4 (where the autoconfiguration didn't exist yet). I agree with the observation that we shouldn't merge producer and consumer properties. Thanks for pointing it out - we'll review this in the next couple days.

**Comment by mbogoevici** [comment] 2017-07-12 14:55
Marking it as a duplicate of #142

**Closed by mbogoevici** 2017-07-12 14:55 UTC
Labels: duplicate

**Comment by tschuettel** [comment] 2017-07-25 19:43
Thank you for fixing. This problem currently keeps us from upgrading to the Dalston release train. Is it possible to backport this to 1.2.x?
