### ISSUE TITLE
Deserialization of contentType header fails when tracing is enabled

### ISSUE THREAD

**Issue by nikolajbrinch** [spring-cloud/spring-cloud-stream-binder-kafka#838] opened 2020-02-03 07:59 UTC
Having Sleuth enabled, enables SleuthDefaultKafkaHeaderMapper, which will encode all headers as byte arrays when producing events. The consumer cannot deserialize the contentType header, as it does not understand the byte array, which resolves in an exception

```
Caused by: java.lang.IllegalArgumentException: Unknown type for contentType header value: class [B
	at org.springframework.messaging.converter.DefaultContentTypeResolver.resolve(DefaultContentTypeResolver.java:76)
	at org.springframework.messaging.converter.AbstractMessageConverter.getMimeType(AbstractMessageConverter.java:265)
	at org.springframework.messaging.converter.AbstractMessageConverter.supportsMimeType(AbstractMessageConverter.java:251)
	at org.springframework.messaging.converter.MappingJackson2MessageConverter.canConvertFrom(MappingJackson2MessageConverter.java:144)
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:194)
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70)
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.convertPayload(SmartMessageMethodArgumentResolver.java:120)
	at org.springframework.cloud.stream.config.SmartMessageMethodArgumentResolver.resolveArgument(SmartMessageMethodArgumentResolver.java:84)
	at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:117)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:148)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:116)
	at org.springframework.cloud.stream.binding.StreamListenerMessageHandler.handleRequestMessage(StreamListenerMessageHandler.java:55)
	... 32 more
```

If we turn off messaging in the the Sleuth configuration it seems to work fine

```
spring:
  sleuth:
    messaging:
      kafka:
        enabled: false
        mapper:
          enabled: false
```

It starts working, but this doesn't seem right. I expect the system to work with the default configuration.

Out producer is sending to a MessageChannel and the consumer is a StreamListener.

I can see from the documentation when messaging for Kafka for Sleuth is disabled that it is using a BinderHeaderMapper in stead og the SleuthDefaultKafkaHeaderMapper. 
The BinderHeaderMapper is new in 3.0.0 and has the following Javadoc:

```
Custom header mapper for Apache Kafka. This is identical to the {@link org.springframework.kafka.support.DefaultKafkaHeaderMapper} from spring Kafka. This is provided for addressing some interoperability issues between Spring Cloud Stream 3.0.x and 2.x apps, where mime types passed as regular {@link MimeType} in the header are not de-serialized properly.
Once those concerns are addressed in Spring Kafka, we will deprecate this class and remove it in a future binder release.
```

Which I find rather confusing?

**Comment by sabbyanandan** [comment] 2020-03-10 14:59
Hi, @nikolajbrinch. This has been addressed in https://github.com/spring-cloud/spring-cloud-stream/commit/2dc7e89345158d8630cfdd91d7c99ff756a7dbe7 — please retry with `3.0.3.RELEASE`/`Horsham.SR3` (Hoxton.SR3).

**Comment by santhoshpt** [comment] 2020-03-12 05:41
Hi, @sabbyanandan.  I'm getting the same exception after upgrading the spring boot 2.2.5.  I had put more details at https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/863. Could you check once and let me know whether the dependencies are correct?

**Comment by sobychacko** [comment] 2020-04-06 19:41
Closing this issue as this is a duplicate of #863. We are going to address the root cause of this in core.

**Closed by sobychacko** 2020-04-06 19:41 UTC
