### ISSUE TITLE
kafka stream memory leak

### ISSUE THREAD

**Issue by zwjsexcalibur** [spring-cloud/spring-cloud-stream-binder-kafka#883] opened 2020-04-20 05:39 UTC
when I use spring-cloud-stream-binder-kafka-core-3.0.3.RELEASE ,I find an exception.If kafka server down and the application start for a moment ,I meet an exception like below:
~~~~
Caused by: java.util.concurrent.TimeoutException: null
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:108) ~[kafka-clients-2.3.1.jar:na]
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:272) ~[kafka-clients-2.3.1.jar:na]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicAndPartitions(KafkaTopicProvisioner.java:361) ~[spring-cloud-stream-binder-kafka-core-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopicIfNecessary(KafkaTopicProvisioner.java:335) ~[spring-cloud-stream-binder-kafka-core-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.provisioning.KafkaTopicProvisioner.createTopic(KafkaTopicProvisioner.java:312) ~[spring-cloud-stream-binder-kafka-core-3.0.3.RELEASE.jar:3.0.3.RELEASE]
	... 28 common frames omitted

2020-04-20 11:22:37.743  INFO 6464 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2020-04-20 11:22:37.784  WARN 6464 --- [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [spring.cloud.inetutils] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 sun.misc.Unsafe.park(Native Method)
 java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
 java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
 java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
 java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
2020-04-20 11:22:37.788  INFO 6464 --- [           main] ConditionEvaluationReportLoggingListener : 
~~~
I think it is not an big problem，but I want to know wheather is my using mistake?

**Comment by sobychacko** [comment] 2020-04-20 13:51
@zwjsexcalibur I don't think that the second exception stack trace in the logs you provided above is caused by the binder or Spring Cloud Stream. Looks like some other dependencies are causing that. Not sure what we can do further to triage it. I am closing the issue. Feel free to re-open with more details to reproduce if you are having more issues with this.

**Closed by sobychacko** 2020-04-20 13:51 UTC
