### ISSUE TITLE
Please bring in log4j

### ISSUE THREAD

**Issue by joshlong** [spring-cloud/spring-cloud-stream-binder-kafka#279] opened 2018-01-09 17:07 UTC
A stock start.spring.io app with the Kafka binder and without log4j throws an exception and fails to start.

**Comment by olegz** [comment] 2018-01-09 17:16
It is currently there as `test` scope so should be simple enough

**Comment by olegz** [comment] 2018-01-09 20:49
Merged!

**Closed by olegz** 2018-01-09 20:49 UTC
Labels: in pr

**Comment by garyrussell** [comment] 2018-01-25 02:19
The root cause is the apps initializr configures 1.3.x apps when you select boot 2; 1.3.x apps are not compatible with boot 2.

The 2.0.0.BS kafka binder has no dependency on the Kafka scala jars (aside from test scope) and thence no dependency on log4j.

IMHO, the initializr shouldn't offer Boot 2.0 until the starters are 2.0 compatible.
